import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeContextProvider } from "./context/ThemeContext";
import Navbar from "@/components/landing/Navbar";

const inter = Inter({
  subsets: ["latin"],
});



export const metadata = {
  title: "QueueLess",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${inter.className} h-full antialiased`}
    >
      <head>
        <script id="theme-script">
          {`
          const savedTheme = localStorage.getItem("dark");

            if (savedTheme === "true") {
            document.documentElement.classList.add("dark");
            }
        `}
        </script>
      </head>
      <body className="min-h-full flex flex-col">
        <ThemeContextProvider>
           {/* <Navbar /> */}
          {children}
        </ThemeContextProvider>
      </body>
    </html>
  );
}
